---
apiVersion: v1
kind: Secret
metadata:
  namespace: demo
  name: vault-token
data:
  #
  # vault auth-enable userpass
  # vault write auth/userpass/users/demo password=SOME_PASSWORD policies=root
  #
  vault-token.yml: |
    method: userpass
    username: demo
    password: SOME_PASSWORD
