---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: demo
  name: vault-demo
spec:
  replicas: 1
  selector:
    name: vault-demo
  template:
    metadata:
      labels:
        name: vault-demo
    spec:
      containers:
      - name: vault-sidekick
        image: gambol99/vault-sidekick:0.0.1
        args:
          - -logtostderr=true
          - -v=4
          - -tls-skip-verify=true
          - -auth=/etc/token/vault-token.yml
          - -output=/etc/secrets
          - -cn=secret:db:up=30s,rv=true
          - -cn=pki:example-dot-com:cn=demo.example.com,fmt=cert,fn=demo.example.com
          - -vault=https://vault.services.cluster.local:8200
        volumeMounts:
          - name: secrets
            mountPath: /etc/secrets
          - name: token
            mountPath: /etc/token
      - name: apache
        image: fedora/apache
        ports:
        - containerPort: 80
        volumeMounts:
          - name: secrets
            mountPath: /etc/secrets
      volumes:
        - name: secrets
          emptyDir: {}
        - name: token
          secret:
            secretName: vault-token
